version: '3.1'

networks:
  booker:

services:
  db:
    image: postgres
    container_name: booker_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - booker

  app:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        PORT: ${APP_PORT}
    container_name: booker_app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      APP_PORT: ${APP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - booker
    depends_on:
      - "db"